export enum expenseErrorCodes {
  GENERIC = "GENERIC_ERROR",
  MEMBER_NOT_FOUND_IN_GROUP = "MEMBER_NOT_FOUND_IN_GROUP",
  EXPENSE_NOT_FOUND = "EXPENSE_NOT_FOUND",
  CANNOT_BE_YOURSELF_MEMBERID = "CANNOT_BE_YOURSELF_MEMBERID",
}
