export enum multerErrorCodes {
  GENERIC = "GENERIC_ERROR",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  CSV_TOO_LARGE = "CSV_TOO_LARGE",
  NO_FILE_UPLOADED = "NO_FILE_UPLOADED",
  CSV_INVALID_FORMAT = "CSV_INVALID_FORMAT",
  CSV_INVALID_COLUMNS = "CSV_INVALID_COLUMNS",
}
