export enum groupMemberErrorCodes {
  GENERIC = "GENERIC_ERROR",
  MEMBER_IS_ALREADY_GROUP = "MEMBER_IS_ALREADY_GROUP",
  MEMBER_DOES_NOT_EXIST = "MEMBER_DOES_NOT_EXIST",
  GROUP_DOES_NOT_EXIST = "GROUP_DOES_NOT_EXIST",
}
