export enum ErrorCodes {
  GENERIC = "GENERIC_ERROR",
  MISSING_OR_INVALID_PARAMETERS = "MISSING_OR_INVALID_PARAMETERS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  GROUP_ALREADY_EXISTS = "GROUP_ALREADY_EXISTS",
  USER_NOT_IN_GROUP = "USER_NOT_IN_GROUP",
}
