export enum paymentErrorCodes {
  GENERIC = "GENERIC_ERROR",
  EXPENSE_NOT_FOUND = "EXPENSE_NOT_FOUND",
  EXPENSE_ALREADY_PAID = "EXPENSE_ALREADY_PAID",
  NO_SPLIT_FOUND = "NO_SPLIT_FOUND",
  EXPENSE_SPLIT_ALREADY_PAID = "EXPENSE_SPLIT_ALREADY_PAID",
}
